embedding_dim= 128
filter_sizes="3,4,5"
num_filters= 128
dropout_keep_prob= 0.5
l2_reg_lambda = 3.0
batch_size= 64
num_epochs= 100
evaluate_every=100
checkpoint_every= 100
num_checkpoints= 5
allow_soft_placement=True
log_device_placement=False
checkpoint_dir= ""
eval_train= False
dev_sample_percentage = 0.1
hidden_size = 128
learning_rate = 1e-3
word2vec = "data/word2vec.model"
display_every = 10